; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
platform = teensy@5.0.0
;platform_packages = framework-arduinoteensy @ https://github.com/hatchjaw/framework-arduinoteensy
platform_packages = framework-arduinoteensy @ symlink://./framework-arduinoteensy
board = teensy41
framework = arduino
upload_protocol = teensy-gui
build_flags =
;    -DWAIT_FOR_SERIAL
    -DAUDIO_SAMPLE_RATE_EXACT=48000
    -Wno-psabi
lib_deps =
    https://github.com/hatchjaw/QNEthernet#6dcab8489bae38da99d4277994e1c51acb39501b
; So pio finds TimeLib.h...
lib_ldf_mode = deep+

[env:clock-authority-usb-audio]
build_src_filter =
    +<clock-authority-usb-audio.cpp>
build_flags =
    ${env.build_flags}
    -DUSB_AUDIO

[env:clock-subscriber]
build_src_filter =
    +<clock-subscriber.cpp>
build_flags =
    ${env.build_flags}
    -DAUDIO_BLOCK_SAMPLES=32

[env:wfs-module]
build_src_filter =
    +<wfs-module.cpp>
build_flags =
    ${env.build_flags}
    -DAUDIO_BLOCK_SAMPLES=32
    -DNUM_SOURCES=16
;    -DUSE_SI_SMOO
lib_deps =
    ${env.lib_deps}
    https://github.com/hatchjaw/teensy-osc#functional
